import { Command, Flags } from "@oclif/core"
import { CommandSpec, runResourceCommand } from "../../executor.js"

export class callsList extends Command {
    static description = ` Retrieve a list of phone Calls made to and from the specified account, sorted from date created, newest to oldest.`
    static examples = [
        "<%= config.bin %> calls:list",
        "<%= config.bin %> calls:list --status ringing --json",
        "<%= config.bin %> calls:list --quiet",
        "<%= config.bin %> calls:list --fields callId,status,from,to",
    ]

    static flags = {
        to: Flags.string({
            char: "T",
            description: "Only show Calls to this phone number.",
            required: false,
        }),
        from: Flags.string({
            char: "f",
            description: "Only show Calls from this phone number.",
            required: false,
        }),
        status: Flags.string({
            char: "S",
            description:
                "Only show Calls currently in this status. May be queued, ringing, inProgress, canceled, completed, failed, busy, or noAnswer.",
            required: false,
        }),
        startTime: Flags.string({
            char: "s",
            description:
                "Only show Calls that started at or after this time, given as YYYY-MM-DD hh:mm:ss.",
            required: false,
        }),
        endTime: Flags.string({
            char: "e",
            description:
                "Only show Calls that ended at or before this time, given as YYYY-MM- DD hh:mm:ss.",
            required: false,
        }),
        parentCallId: Flags.string({
            char: "P",
            description: "Only show Calls generated by the call with this ID.",
            required: false,
        }),
        active: Flags.string({
            char: "a",
            description: "Flag defaults to false. Set true to list active calls.",
            required: false,
            options: ["true", "false"],
        }),
        next: Flags.boolean({ char: "n", description: "Displays the next page of output." }),
        json: Flags.boolean({
            description:
                "Output as a structured JSON envelope with request metadata. Also enabled globally via FREECLIMB_OUTPUT_FORMAT=json.",
            default: false,
        }),
        quiet: Flags.boolean({
            description:
                "Output only resource IDs, one per line. Useful for piping into other commands.",
            default: false,
        }),
        fields: Flags.string({
            description:
                "Comma-separated list of fields to include in the response. Limits output to protect context windows when used by agents.",
        }),
        help: Flags.help({ char: "h" }),
    }

    async run() {
        const spec: CommandSpec = {
            topic: "calls",
            commandName: "list",
            endpoint: "Calls",
            method: "GET",
            quietIdKey: "callId",
            supportsNext: true,
            validations: [
                { source: "flags", key: "parentCallId", rule: "resourceId" },
                { source: "flags", key: "to", rule: "controlChars" },
                { source: "flags", key: "from", rule: "controlChars" },
                { source: "flags", key: "status", rule: "controlChars" },
                { source: "flags", key: "startTime", rule: "controlChars" },
                { source: "flags", key: "endTime", rule: "controlChars" },
            ],
            buildParams: (args, flags) => ({
                to: flags.to,
                from: flags.from,
                status: flags.status,
                startTime: flags.startTime,
                endTime: flags.endTime,
                parentCallId: flags.parentCallId,
                active: typeof flags.active === "undefined" ? undefined : flags.active === "true",
            }),
        }
        await runResourceCommand(this, spec)
    }
}
